export class Cooperativesociety {

  societyId: number = 0;//autogenerated
  societyName: string = '';
  headOfSociety: string = '';
  village: string = '';
  district: string = '';
  pincode: string = '';
}
