export class Registeredsocietyvoters {

    voterId: number=0;//autogenerated
    voterIdCardNo: number=0;
    firstName: string="";
    lastName: string="";
    gender: string="";
    mobileNo: string="";
    emailId: string="";
    address: string="";
    district: string="";
    pincode: string="";
    castedVote: boolean=true;
}
