import { Cooperativesociety } from './cooperativesociety';
import { Nominatedcandidate } from './nominatedcandidate';
import { Registeredsocietyvoters } from './registeredsocietyvoters';
export class Votedlist {
  
  id: number = 0; //autogenerated
  registeredSocietyVoters: Registeredsocietyvoters[]=[];
  nominatedcandidate: Nominatedcandidate[]=[];
  cooperativesociety: Cooperativesociety[]=[];

  
}
